// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADVw5bXNdVZbaOXV8Zw9gwG2Dr9pyoMXA',
    appId: '1:366329643683:web:6413949c2963796e4a3516',
    messagingSenderId: '366329643683',
    projectId: 'remidipab1462300022',
    authDomain: 'remidipab1462300022.firebaseapp.com',
    storageBucket: 'remidipab1462300022.firebasestorage.app',
    measurementId: 'G-E94JE26DTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2fx0Fp88JcqviHqCJU_8F9kFi-Qesw8',
    appId: '1:366329643683:android:7c65af88948b46304a3516',
    messagingSenderId: '366329643683',
    projectId: 'remidipab1462300022',
    storageBucket: 'remidipab1462300022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLFEnYEsugAF3rryy9JJkX1qMTyS6rQU',
    appId: '1:366329643683:ios:7b9e521ff2ebeea74a3516',
    messagingSenderId: '366329643683',
    projectId: 'remidipab1462300022',
    storageBucket: 'remidipab1462300022.firebasestorage.app',
    iosBundleId: 'com.example.remidipab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLFEnYEsugAF3rryy9JJkX1qMTyS6rQU',
    appId: '1:366329643683:ios:7b9e521ff2ebeea74a3516',
    messagingSenderId: '366329643683',
    projectId: 'remidipab1462300022',
    storageBucket: 'remidipab1462300022.firebasestorage.app',
    iosBundleId: 'com.example.remidipab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADVw5bXNdVZbaOXV8Zw9gwG2Dr9pyoMXA',
    appId: '1:366329643683:web:4e2954f83f45eb964a3516',
    messagingSenderId: '366329643683',
    projectId: 'remidipab1462300022',
    authDomain: 'remidipab1462300022.firebaseapp.com',
    storageBucket: 'remidipab1462300022.firebasestorage.app',
    measurementId: 'G-2DXSFCCVFL',
  );
}
